In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [65]:
df = pd.read_excel("indo_12_1.xls", skiprows=3, na_values='-')
df.head(10)
df.isnull().sum()
df = df.fillna(0)
df.isnull().sum()
df.head(10)
df['provinsi'] = df.iloc[:,0]
df.head(10)
# len(df)
# np.full((1, 36), 10)

,Unnamed: 0,1971,1980,1990,1995,2000,2010,provinsi
0,Aceh,2008595.0,2611271.0,3416156.0,3847583.0,3930905.0,4494410.0,Aceh
1,Sumatera Utara,6621831.0,8360894.0,10256027.0,11114667.0,11649655.0,12982204.0,Sumatera Utara
2,Sumatera Barat,2793196.0,3406816.0,4000207.0,4323170.0,4248931.0,4846909.0,Sumatera Barat
3,Riau,1641545.0,2168535.0,3303976.0,3900534.0,4957627.0,5538367.0,Riau
4,Jambi,1006084.0,1445994.0,2020568.0,2369959.0,2413846.0,3092265.0,Jambi
5,Sumatera Selatan,3440573.0,4629801.0,6313074.0,7207545.0,6899675.0,7450394.0,Sumatera Selatan
6,Bengkulu,519316.0,768064.0,1179122.0,1409117.0,1567432.0,1715518.0,Bengkulu
7,Lampung,2777008.0,4624785.0,6017573.0,6657759.0,6741439.0,7608405.0,Lampung
8,Kepulauan Bangka Belitung,0.0,0.0,0.0,0.0,900197.0,1223296.0,Kepulauan Bangka Belitung
9,Kepulauan Riau,0.0,0.0,0.0,0.0,0.0,1679163.0,Kepulauan Riau

In [77]:
fig = plt.figure(figsize=(20,10))
ax = fig.add_subplot(231, projection='3d')

i = 1
x = np.arange(len(df))
y = np.arange(10)
z = np.zeros(10)

dx = np.ones(len(df))
dy = np.ones(10)
dz = df.iloc[:,1] # data

plt.title("Jumlah Penduduk 1971")
ax.bar3d(x,y,z, dx, dy,dz)
ax.set_zlabel("Jumlah Penduduk", )
# ax.set_yticks(df['provinsi'])
ax.set_yticklabels(df['provinsi'])
# ax.set_

plt.show()

c:\users\nadian\anaconda3\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py:2480: UserWarning: x, y, and z must be the same length.
  warnings.warn('x, y, and z must be the same length.')

ValueError: operands could not be broadcast together with shapes (60,1) (216,4)